// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtxyTjz7R_l_SdYPCwyv3jHPvhIPOtpg',
    appId: '1:675869314622:web:3f94f6bf0c6d65c91f0b6f',
    messagingSenderId: '675869314622',
    projectId: 'otpauth-74c7c',
    authDomain: 'otpauth-74c7c.firebaseapp.com',
    storageBucket: 'otpauth-74c7c.appspot.com',
    measurementId: 'G-SQHH8ZHXXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSTuemnR_oVQhK7A-xAzkg4r2506em2Wo',
    appId: '1:675869314622:android:7b8e3c1399da61841f0b6f',
    messagingSenderId: '675869314622',
    projectId: 'otpauth-74c7c',
    storageBucket: 'otpauth-74c7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMekCeC-SJxRFA2uYZTEEwqyaGV2iInFM',
    appId: '1:675869314622:ios:3e74b081d20bf6491f0b6f',
    messagingSenderId: '675869314622',
    projectId: 'otpauth-74c7c',
    storageBucket: 'otpauth-74c7c.appspot.com',
    iosBundleId: 'com.pksoft.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMekCeC-SJxRFA2uYZTEEwqyaGV2iInFM',
    appId: '1:675869314622:ios:3e74b081d20bf6491f0b6f',
    messagingSenderId: '675869314622',
    projectId: 'otpauth-74c7c',
    storageBucket: 'otpauth-74c7c.appspot.com',
    iosBundleId: 'com.pksoft.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrtxyTjz7R_l_SdYPCwyv3jHPvhIPOtpg',
    appId: '1:675869314622:web:b0f74dd1340ffbd21f0b6f',
    messagingSenderId: '675869314622',
    projectId: 'otpauth-74c7c',
    authDomain: 'otpauth-74c7c.firebaseapp.com',
    storageBucket: 'otpauth-74c7c.appspot.com',
    measurementId: 'G-W3V616FYH5',
  );
}
